site_name: Hotmart Python
repo_url: https://github.com/im-voracity/hotmart-python
repo_name: im-voracity/hotmart-python
edit_uri: tree/main/docs

theme:
  name: dracula
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css
