---
name: Checks

on:
  pull_request:
    branches:
      - master

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.1"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        id: install
        run: poetry install

      - name: Run tests
        id: tests
        run: |
          poetry env shell
          poetry run python -m unittest discover -s tests
        if: steps.install.outcome == 'success'

      - name: Run flake8
        id: flake8
        run: |
          poetry env shell
          poetry run flake8
        if: steps.install.outcome == 'success'
